version: "3.0"

services:
  dnfm-mongo:
    image: mongo:latest
    container_name: "my-mongo-db"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cr37
    volumes:
      - "./db_dump:/dp_dump"
    networks:
      - backend

  dnfm_flaskapp:
    container_name: "my-flask-app"
    restart: always
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    ports:
      - 8800:8800
    command: ./flask/docker-entrypoint-flask.sh
    depends_on:
      - dnfm-mongo
    links:
     - dnfm-mongo:dnfm-mongo
    networks:
      - frontend
      - backend

  dnfm_nginx:
    container_name: "my-nginx"
    image: nginx
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - dnfm_flaskapp
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

